name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull devhub3/devhub-backend:latest
      - name: Delete old container
        run: sudo docker rm -f devhub-backend-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name devhub-backend-container -e ACCESS_KEY=${{secrets.ACCESS_KEY}} -e SECRET=${{secrets.SECRET}} -e BUCKET_NAME=${{secrets.BUCKET_NAME}} -e SESSION_TOKEN=${{secrets.SESSION_TOKEN}} -e REGION=${{secrets.REGION}} devhub3/devhub-backend